### ISSUE TITLE
Parsing dialect file fails on Windows

### ISSUE THREAD

**Issue by curzona** [cucumber/gherkin3#93]
`import gherkin3` on Windows results in the following error:

```
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from gherkin3.parser import Parser
  File "c:\users\curzona\desktop\gherkin-python\gherkin3\parser.py", line 4, in <module>
    from .token_matcher import TokenMatcher
  File "c:\users\curzona\desktop\gherkin-python\gherkin3\token_matcher.py", line 2, in <module>
    from .dialect import Dialect
  File "c:\users\curzona\desktop\gherkin-python\gherkin3\dialect.py", line 12, in <module>
    DIALECTS = json.load(file, encoding='utf-8')
  File "C:\python27\lib\json\__init__.py", line 286, in load
    return loads(fp.read(),
  File "C:\python27\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 731: character maps to <undefined>
```

**Comment by curzona** [comment]
On Windows, files other than ASCII should be opened with `'b'` mode, this includes unicode files.
See https://docs.python.org/2/tutorial/inputoutput.html#reading-and-writing-files

**Comment by brasmusson** [comment]
Thanks for notifying us. However, opening with `'b'` mode, does not work with Python3, since the data type read will be `bytes` instead of `str` (it neither works on Windows nor on Linux with Python3). What I found out was working was passing the argument `encoding='utf8'` to `io.open` (7833ee9). This worked for me both on Windows native (CPython I believe) and on Linux, in both cases both with Python 2.7 and Python 3.4.

**Comment by curzona** [comment]
@brasmusson Thanks! I missed testing with Python3, I'm glad you caught that.
